version: 1

paths:
  # Use the improved dictionary as the default. Put the file here or update the path.
  cultural_dictionary: config/sa_cultural_dict_improved.json
  # Prefer CSV; JSON also supported. Update if yours lives elsewhere.
  stopwords: config/sa_stopwords.csv
  # Technical→display category mapping (file below)
  category_mapping: config/category_mapping.json

  # Data in / out
  integrated_comments: processed_data/integrated_comments.parquet
  topics_output_dir: processed_data/topics
  cache_dir: processed_data/cache

modeling:
  # Choose the engine; we’ll wire the modeling code to honor this.
  engine: bertopic            # options: bertopic, sklearn_lda
  random_state: 42

  # Per-creator requirements
  per_creator_min_comments: 100
  topic_min_count_to_keep: 5        # drop tiny/fragment topics

  # Text vectorization (used for both BERTopic + LDA TF-IDF)
  ngram_range: [1, 3]
  max_features: 20000               # large vocab for accuracy
  min_df: 2
  max_df: 0.85
  sublinear_tf: true
  norm: l2
  strip_accents: unicode

  # Cultural guidance
  use_cultural_guidance: true
  vocabulary_from_dictionary: true   # seed the vocab with cultural terms
  phrase_protection: true            # protect multi-word terms (underscoring)
  seed_confidence: 0.35              # how strongly to bias names/titles

  # BERTopic params (only used when engine == bertopic)
  umap:
    n_neighbors: 15
    n_components: 10
    min_dist: 0.0
    metric: cosine
    random_state: 42
  hdbscan:
    min_cluster_size: 15
    metric: euclidean
    cluster_selection_method: eom
    prediction_data: true
  ctfidf:
    reduce_frequent_words: true

  # LDA params (only used when engine == sklearn_lda)
  lda:
    n_topics: auto                   # auto = choose by data size
    doc_topic_prior: 0.1
    topic_word_prior: 0.1
    max_iter: 200
    learning_decay: 0.7
    learning_offset: 50.0

naming:
  # How we label topics in the UI
  strategy: category_then_terms      # options: category_then_terms, top_terms
  top_terms: 5
  fallback_category: General

ui:
  display_category_order:
    - Language & Expression
    - Social & Greeting
    - Food & Culture
    - Music & Entertainment
    - Place & Location
    - Sports & Recreation
    - Identity & Philosophy
    - Health & Traditional
    - Work & Economy
    - Conflict & Confrontation
    - General South African
